Create table vehicle_category (categoryID varchar(5) NOT NULL,vehicle_type varchar (15) NOT NULL,insurance_group varchar (15) NOT NULL, PRIMARY KEY (categoryID) );
Create table Gender (gender_ID varchar (5) NOT NULL, gender varchar (15) NOT NULL, pronnouns varchar(10) NOT NULL, PRIMARY KEY (gender_ID) );
Create table Address(street varchar (20) NOT NULL, street_number int NOT NULL, postal_code int NOT NULL, city varchar (20) NOT NULL, address_id varchar(5) NOT NULL,country varchar (30) PRIMARY KEY (address_id) );
Create table Clients (fullname varchar (30) NOT NULL,contract_code varchar(20) NOT NULL, email varchar (30) NOT NULL, phonenumber1 varchar (20) NOT NULL,phonenumber2 varchar(20),driver bool NOT NULL, PRIMARY KEY (contract_code));
Create table Drivers (fullname varchar(30) NOT NULL, gender_id varchar(5) NOT NULL,birthdate date NOT NULL,address_id varchar(5) NOT NULL,drivers_license_number varchar (20) NOT NULL, contract_code varchar(20) NOT NULL, PRIMARY KEY (drivers_license_number),FOREIGN KEY (gender_id) references gender on delete set null,FOREIGN KEY (address_id) references address on delete set null, FOREIGN KEY (contract_code) references clients on delete set null  )
Create table Vehicles (car_vin varchar (20) NOT NULL, registration_number varchar (7) NOT NULL, manufacturer varchar (15) NOT NULL, model varchar (20) NOT NULL,color varchar (10) NOT NULL, release_year int NOT NULL, cur_value varchar (10) NOT NULL, contract_code varchar(20) NOT NULL, categoryID varchar (5) NOT NULL, driver varchar(20) NOT NULL, PRIMARY KEY (registration_number), FOREIGN KEY (categoryID) references vehicle_category on delete set null, FOREIGN KEY  (contract_code) references Clients on delete set null,FOREIGN KEY (driver) references Drivers on delete set null );
Create table Insurance (insuranceID varchar (5) NOT NULL,contract_code varchar (20) NOT NULL, car varchar (7) NOT NULL, contract_start_date date NOT NULL, contract_end_date date NOT NULL, valid_con bool NOT NULL, con_cost varchar (10) NOT NULL, driver varchar (20) NOT NULL, categoryID varchar (5) NOT NULL, PRIMARY KEY (insuranceID), FOREIGN KEY (contract_code) references Clients on delete set null, FOREIGN KEY(car) references Vehicles on delete set null, FOREIGN KEY (categoryID) references vehicle_category on delete set null, foreign key (driver) references Drivers on delete set null);
CREATE TABLE Violations (violation_ID varchar, violation_date date,violation_time time, short_descreption varchar, Primary Key (violation_ID));
CREATE TABLE Caused_By (caused_by_id varchar, registration_number varchar,violation_ID varchar,driver varchar, primary key (caused_by_id), foreign key (violation_id) references Violations on delete set null, foreign key (registration_number) references vehicles on delete set null, foreign key (driver) references Drivers on delete set null);

COPY caused_by (caused_by_id, registration_number,violation_ID ,driver) FROM 'C:\Users\Public\Caused_by.csv' DELIMITER ',' CSV HEADER;
COPY Violations (violation_ID, violation_date,violation_time, short_descreption) FROM 'C:\Users\Public\Violations.csv' DELIMITER ',' CSV HEADER;
COPY Gender (gender_id,gender,pronnouns) FROM 'C:\Users\Public\Gender.csv' DELIMITER ',' CSV HEADER;
COPY vehicle_category (categoryid,vehicle_type,insurance_group) FROM 'C:\Users\Public\vehicle_category.csv' DELIMITER ',' CSV HEADER;
COPY Clients (fullname,contract_code,email,phonenumber1,phonenumber2,driver) FROM 'C:\Users\Public\Clients.csv' DELIMITER ',' CSV HEADER;
COPY Address (street,street_number,postal_code,city,address_id,country) FROM 'C:\Users\Public\Address.csv' DELIMITER ',' CSV HEADER;
COPY Drivers (fullname,gender_id,birthdate,address_id,drivers_license_number,contract_code) FROM 'C:\Users\Public\Drivers.csv' DELIMITER ',' CSV HEADER;
COPY Vehicles (car_vin,registration_number,manufacturer,model,color,release_year,cur_value,contract_code,categoryID,driver) FROM 'C:\Users\Public\Vehicles.csv' DELIMITER ',' CSV HEADER;
COPY insurance (insuranceID,contract_code,car,contract_start_date,contract_end_date,valid_con,con_cost,categoryid) FROM 'C:\Users\Public\Insurance.csv' DELIMITER ',' CSV HEADER;

